name: Greetings Update

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update README
        run: |
          DATE=$(TZ="Asia/Kolkata" date +"%d-%m-%Y %H:%M IST")
          HOUR=$(TZ="Asia/Kolkata" date +'%H')

          if [ $HOUR -ge 5 ] && [ $HOUR -lt 17 ]; then
            MSG="Hi 👋 there, Good Morning"
          else
            MSG="Hi 👋 there, Good Evening"
          fi

          sed -i "s|Hi 👋 there,.*|$MSG<br>|" README.md
          sed -i "s|Last Updated:.*|Last Updated: $DATE|" README.md

      - name: Commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Auto update greeting" || echo "No changes"
          git push
